### ISSUE TITLE
Tooltip partly offscreen (left v. right)

### ISSUE THREAD

**Issue by craig-at-rsg** [nozzle/nzTour#36] opened 2016-07-12 20:10 UTC
I have a tooltip showing on the left, that should show on the right, on an iPhone 5S - it goes offscreen on the side it's shown. Is this something I'm doing wrong? Is there some way I could get this working without having to hard-code the side ot show it on?

![tooltip on wrong side](https://cloud.githubusercontent.com/assets/6004181/16781723/85636a5a-484a-11e6-914c-d4b29fc86e64.PNG)

Thanks,
Craig

**Comment by lebolo** [comment] 2016-07-12 20:27
What version are you using? And can you post your tour configurations?

**Comment by craig-at-rsg** [comment] 2016-07-12 20:50
Version 1.1.

Here are the config values I'm setting:
{"dark":false,"mask":{"clickExit":true},"scrollBox":"[nav-view='active'] .scroll"}

**Comment by craig-at-rsg** [comment] 2016-07-13 13:30
Do you maybe have a debug version that logs out some values showing which placement was chosen? If you do, I could run with that and report back the results for this one.

**Comment by lebolo** [comment] 2016-07-13 14:12
How about the individual tour step configs? From the screenshot, it looks like the tooltip can't fit on the bottom or the right, so it goes to the top (the default positions the tour tries are `placementPriority: ['bottom', 'right', 'top', 'left']`)

If you're just copying in the minified version of the code into your project, then you can use the un-minified version (_nzTour/dist/nz-tour.js_) and add `console.log` statements to debug. You can start at the `bottom()`, `right()`, `top()`, and `left()` functions around [line 700](https://github.com/nozzle/nzTour/blob/master/dist/nz-tour.js#L700). Maybe print out the results of the various `if` statements and see why the tour decides that top is the correct placement.

I don't know how complex your project is, but it will be hard for us to debug unless you can create a Plunkr for us to reproduce the issue. You can start from this [plnkr](https://plnkr.co/edit/tpl:1opxGgUIhFZRpnxRl4qc).

**Comment by craig-at-rsg** [comment] 2016-07-13 19:00
I think I found it. Here's the top-left check:

`if (dims.target.offset.fromRight + dims.target.width > maxWidth)`

and this log line:

`console.log('top right (' + dims.target.offset.fromRight + ' + ' + dims.target.width + ' = ' + (dims.target.offset.fromRight + dims.target.width) + ' <= ' + maxWidth + ')');`

outputs:
top right (160 + 80 = 240 <= 250)

So, there wasn't enough room on the left, so we got stuck on the right, because of

`// Right, I guess...`

I think if the maxWidth is < 1/2 of the screen width then we're ok (even for a 1 pixel target). The iPhone 5S has a 320px wide screen, so we'd need 159 or lower as the maxWidth to be completely safe, but I'm going to use 200px, which will probably work in most cases. 

A related question - it there a way to make maxWidth configurable, so I don't need to maintain my own copy of the project? I noticed it's in the css (`#nzTour-box{width:250px...`) as well.

**Comment by lebolo** [comment] 2016-07-13 19:12
I'm not familiar with the `.styl` files that nzTour uses to ultimately build the CSS, but it seems like it would be difficult to have the same **runtime configurable** `maxWidth` parameter in **both** the [javascript](https://github.com/nozzle/nzTour/blob/master/src/nz-tour.js#L297) and the [css](https://github.com/nozzle/nzTour/blob/master/src/nz-tour.styl#L32) files.

Maybe @tannerlinsley or someone else can comment?

I don't see any other way around having to maintain your own copy :sob:

**Comment by tannerlinsley** [comment] 2016-07-13 19:17
At the moment, the css max-width is a default which the javascript can override.  We could make that configurable.  

@lebolo, let's chat on Gitter if you're available and @craig-at-rsg, I would accept a PR to allow an override of the max-width in the javascript to make it more configurable.

For everyone within earshot, I've release a new touring module https://tourjs.github.io/tour/ (much smaller, much faster, and has much more potential)

It's built on the concepts and some of the logic from nzTour.

**Comment by lebolo** [comment] 2016-07-20 15:10
Closing this for now (although see #31 for a place to start - if anyone wants to take it up).

**Closed as completed by lebolo** 2016-07-20 15:10 UTC
